var1=input("Introduce una frase:")
var_a=var1.count("a")
var_e=var1.count("e")
var_i=var1.count("i")
var_o=var1.count("o")
var_u=var1.count("u")
print("El número de a es",(var_a)," el número de e es",(var_e)," el número de i es",(var_i)," el número de o es ",(var_o)," y el número de u es",(var_u))